controller_list:
  - name: fake_openmanipulator_arm_controller
    joints:
      - id_11
      - id_12
      - id_13
      - id_14
      - id_15
#  - name: fake_gripper_controller
#    joints:
#      - id_15
#initial:  # Define initial robot poses.
#  - group: openmanipulator_arm
#    pose: arm_zero
#  - group: gripper
#    pose: gripper_open